# Generated by Django 4.1.4 on 2022-12-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
