# Generated by Django 4.1.4 on 2022-12-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_remove_cart_completed_remove_cart_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='id',
        ),
    ]
